schedule:
  TIMEZONE: 'Europe/Moscow'
  check:
    time:
      - '07:00'
      - '10:00'
      - '12:30'
    every:
      - 'monday'
      - 'tuesday'
      - 'wednesday'
      - 'thursday'
      - 'friday'
  daily:
    time:
      - '13:00'
    every:
      - 'monday'
      - 'tuesday'
      - 'wednesday'
      - 'thursday'
github:
  owner: 'qral-scan'
  repo: 'usb'
developer:
  chat_id: ''
  developers:
      - '@perlinleo' : '@lperlin'
